[connections.snowflake]
account = "KHPEYWZ-SHB97026"
user = "ATPETTIT128"
password = "5n0wFl@keR0ck5!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
